[colors.primary]
background = '#0D0D0D'
foreground = '#FFFFFF'

[colors.selection]
text = '#e6e1f7'
background = '#2a243f'

[colors.cursor]
text = '#090415'
cursor = '#c7b3f3'

[colors.normal]
black   = '#1F1F28'
red     = '#ff728f'
green   = '#79f393'
yellow  = '#ffda72'
blue    = '#b49de6'
magenta = '#4b3a70'
cyan    = '#c7b3f3'
white   = '#f4efff'

[colors.bright]
black   = '#95929d'
red     = '#ff9fb2'
green   = '#a5ffb8'
yellow  = '#ffe7a5'
blue    = '#d7c5ff'
magenta = '#decfff'
cyan    = '#eae0ff'
white   = '#faf8ff'
